spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
  main:
    banner-mode: "off"
  profiles:
    active: @spring.profiles.active@
  datasource:
    url: jdbc:h2:mem:dafcbts;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    platform: h2
    username: dafcbts
    password:
  output:
    ansi:
      enabled: always
logging:
 level:
   root: OFF
   org.springframework: OFF